[package]
name = "vidbag2mmd"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "5.0"
image = "0.25.5"
tokio = { version = "1.41.1", features = ["full"] }
ndarray = "0.16.1"
ort = { version = "2.0.0-rc.8", features = [ "cuda", "tensorrt", "openvino" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.3"