[detect]

car_onnx_path = "assets/model/car.onnx"
armor_onnx_path = "assets/model/armor.onnx"

car_conf_thresh = 0.30
armor_conf_thresh = 0.65

car_nms_thresh = 0.50
armor_nms_thresh = 0.75

execution = "CUDA"